server:
  port: 9111
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true

mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: com.ht.znmj.**.entity
  # xml 扫描路径
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

#应用版本号
application-info:
  version: 1.0.0.2
  bit: 32
  cloudFlag: 1